/**
 * Pin & vendor the Kaveh headless bundle.
 *
 *   node scripts/sync-kaveh.mjs <kaveh-commit-sha>
 *
 * Fetches dist-headless/kaveh-headless.js + SHA256 from the PUBLIC Kaveh repo
 * at an exact commit, verifies the hash, and emits src/kaveh-source.ts so the
 * control plane bundles a pinned, hash-checked artifact — never an unpinned
 * remote fetch at runtime (same rule as DATA_PLANE_SOURCE).
 */
import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";

const sha = process.argv[2];
if (!/^[0-9a-f]{40}$/u.test(sha ?? "")) {
  console.error("usage: node scripts/sync-kaveh.mjs <40-hex commit sha>");
  process.exit(2);
}
const base = `https://raw.githubusercontent.com/Alisarani7021/kaveh/${sha}/dist-headless`;
const [src, manifest] = await Promise.all([
  fetch(`${base}/kaveh-headless.js`).then((r) => (r.ok ? r.text() : Promise.reject(new Error(`source ${r.status}`)))),
  fetch(`${base}/SHA256`).then((r) => (r.ok ? r.text() : Promise.reject(new Error(`manifest ${r.status}`)))),
]);
const want = manifest.trim().split(/\s+/u)[0];
const got = createHash("sha256").update(src).digest("hex");
if (want !== got) {
  console.error(`sha256 mismatch: manifest ${want} != fetched ${got}`);
  process.exit(1);
}
// Escape for embedding in a TS template literal.
const esc = src.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");
const ts = `// GENERATED by scripts/sync-kaveh.mjs — do not edit.
// Kaveh headless tenant-node bundle, pinned & hash-verified.
export const KAVEH_SOURCE_COMMIT = "${sha}";
export const KAVEH_SOURCE_SHA256 = "${got}";
export const KAVEH_SOURCE = String.raw\`${esc}\`;
`;
await writeFile(new URL("../src/kaveh-source.ts", import.meta.url), ts);
console.log(`src/kaveh-source.ts ← kaveh@${sha.slice(0, 12)}  ${src.length} B  sha256 ${got.slice(0, 16)}…`);
